[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"
  BUNDLER_VERSION = "2.4.10"
  JEKYLL_ENV = "production"

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
